version: '3.8'

networks:
  student-project:

services:
  app:
    image: backend
    depends_on:
      - mysqldb
    build: ../project
    container_name: mydb
    restart: unless-stopped
    env_file: ./.env
    ports:
      - 5000:5000
    environment:
      - DB_HOST=mysqldb
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_NAME=project
      - DB_PORT=3306
    stdin_open: true
    tty: true
    networks:
      - student-project

  mysqldb:
    image: mysql
    restart: "no"
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=project
    ports:
      - 3307:3306
    volumes:
      - db:/var/lib/mysql
    networks:
      - student-project
    command: 
      --default-authentication-plugin=mysql_native_password
  
volumes: 
  db:
